-- EDA

select * from category;
select * from customers;
select * from inventory;
select * from order_items;
select * from orders;
select * from payments;
select * from products;
select * from seller;
select * from shippings;

-- Business Problems Advance analysis

-- 1.Top selling Products
-- Query the top 10 products by total sale value
-- Challenge:Include product name,total quantity sold and total sales value

-- Adding new column called total_sale

alter table order_items add column total_sale float;
update order_items set total_sale = quantity * price_per_unit;
select * from order_items order by quantity desc;

select oi.product_id,p.product_name,sum(oi.total_sale)
as total_sale,count(o.order_id) as total_orders from orders
as o join order_items as oi
on o.order_id = oi.order_id join products as p
on p.product_id = oi.product_id
group by 1,2 order by 3 desc limit 10;


-- 2.Revenue by category
-- caliculate total revenue generated by each product category.
-- challenge:Include the percentage contribution of each category to total revenue

select p.category_id,c.category_name,sum(oi.total_sale) 
as total_sale,sum(oi.total_sale) / (select sum(total_sale) from order_items) * 100 as contribution
from order_items as oi join products as p
on oi.product_id = p.product_id
left join category as c 
on c.category_id = p.category_id
group by 1,2 order by 3 desc;


-- 3.Average Order Value(AOV)
-- Compute the average order value for each customer

SELECT
    c.customer_id,
    CONCAT(c.first_name, ' ', c.last_name) AS full_name,
    SUM(total_sale) / COUNT(o.order_id) AS AOV,
    COUNT(o.order_id) AS total_orders -- filter
FROM orders AS o
JOIN customers AS c
    ON c.customer_id = o.customer_id
JOIN order_items AS oi
    ON oi.order_id = o.order_id
GROUP BY 1, 2
HAVING count(o.order_id) > 5;


/*
4. Monthly Sales Trend
Query monthly total sales over the past year.
Challenge: Display the sales trend, grouping by month, return current_month sale, last month sale!
*/


select year,month,total_sale as current_total_sale,lag(total_sale,1) over (order by year,month) as last_month_sale from
(select extract(year from o.order_date) as year,extract(month from o.order_date) as month,
round(sum(oi.total_sale::numeric),2) as total_sale from orders as o join order_items as oi
on o.order_id = oi.order_id where o.order_date > current_date - interval '3 years'
group by 1,2 order by year,month) as t1

-- 5.customers with no purchase

SELECT *
FROM customers AS c
LEFT JOIN orders AS o
    ON o.customer_id = c.customer_id;


/*
6. Best-Selling Categories by State
Identify the best-selling product category for each state.
Challenge: Include the total sales for that category within each state.
*/


WITH ranking_table AS (
    SELECT
        c.state,
        cat.category_name,
        SUM(oi.total_sale) AS total_sale,
        RANK() OVER (
            PARTITION BY c.state
            ORDER BY SUM(oi.total_sale) DESC
        ) AS rank
    FROM orders AS o
    JOIN customers AS c
        ON o.customer_id = c.customer_id
    JOIN order_items AS oi
        ON o.order_id = oi.order_id
    JOIN products AS p
        ON oi.product_id = p.product_id
    JOIN category AS cat
        ON cat.category_id = p.category_id
    GROUP BY 1, 2
)

SELECT *
FROM ranking_table
WHERE rank = 1;



-- 7.customer lifetime value(CLTV)
-- caliculate the total value of orders placed by each customer over their lifetime
-- challenge:Rank customers based on thei CLTV

select c.customer_id,concat(c.first_name,' ',c.last_name) as full_name 
,sum(total_sale),dense_rank() over(order by sum(total_sale) desc)  as customer_ranking from customers as c 
join orders as o on o.customer_id = c.customer_id
join order_items as oi on o.order_id = oi.order_id
group by 1,2

/*
8. Inventory Stock Alerts
Query products with stock levels below a certain threshold (e.g., less than 10 units).
Challenge: Include last restock date and warehouse information.
*/

select i.inventory_id,p.product_name,i.stock as current_stock_left,
i.last_stock_date,i.warehouse_id from inventory as i join  products as p
on p.product_id = i.inventory_id where i.stock < 10

-- 9.shipping delays
-- Identify orders where the shipping date is later than 7 days after the order date
-- challenge:Include customer,order details and delivery provider

select o.*,c.*,s.shipping_providers from orders as o 
join customers as c on c.customer_id = o.customer_id
join shippings as s on s.order_id = o.order_id
where o.order_date - s.shipping_date > 7

-- 10.payment success Rate
-- caliculate the percentage of successful payments across all orders
-- challenge:Include breakdowns by payment status

select p.payment_status,count(*) as total_payments,
round(count(*) / (select count(*) from payments)::numeric * 100,2) from orders as o 
join payments as p on o.order_id = p.order_id
group by p.payment_status


-- 11.Top performaing seller
-- Find the top 5 sellers based on total sales value
-- challenge:Include both successful and failed orders and display their percentage of successful orders.


with top_sellers as (
select s.seller_id,s.seller_name,sum(total_sale) as total_sale from seller as s
join orders as o on s.seller_id = o.seller_id
join order_items as oi on oi.order_id = o.order_id
group by 1,2 order by 3 desc limit 5
),
sellers_reports AS (
    SELECT 
        o.seller_id,
        ts.seller_name,
        o.order_status,
        COUNT(*) AS order_count
    FROM orders o
    JOIN top_sellers ts 
        ON ts.seller_id = o.seller_id
		where order_status not in ('Pending','Returned')
    GROUP BY 1, 2, 3
)
SELECT seller_id,seller_name,
SUM(CASE WHEN ORDER_STATUS = 'Delivered' THEN order_count ELSE 0 END) AS delivered_orders,
SUM(CASE WHEN ORDER_STATUS = 'Cancelled' THEN order_count ELSE 0 END) AS cancelled_orders,
sum(order_count)
FROM sellers_reports
GROUP BY 1,2
ORDER BY 1;


-- 12.Most returned products
-- Query the top 10 products by the number of returns.
-- challenge:Display the return rate as percentage of total units sold for each product

select p.product_id,p.product_name,count(*) as total_units_sold,
sum(case when o.order_status = 'Returned' then 1 else 0 end) as total_returned,
round(sum(case when o.order_status = 'Returned' then 1 else 0 end)::numeric / count(*) ::numeric * 100,2) as returned_percentage
from order_items as oi
join products as p on oi.product_id = p.product_id
join orders as o on o.order_id = oi.order_id
group by 1,2 order by 5 desc;


-- 13.Inactive Sellers
-- Identify sellers who have not made any sales in last 6 months
-- challenge:show the last sale date and total sales from those sellers


with cte as (
select * from seller where seller_id not in 
(select seller_id from orders where order_date > current_date - interval '1 year')
)

select o.seller_id,max(o.order_date) as last_order_date,
max(oi.total_sale) as last_sale_amount from orders as o
join order_items as oi on o.order_id = oi.order_id
join cte on cte.seller_id = o.seller_id
group by 1


-- 14.Identify customers into returning or new if the customer has done more than 
-- 5 return categoorize them as returning otherwise new
-- challenge:list customers id,name,total orders,total returns

with cte as (
select concat(c.first_name,' ',c.last_name) as full_name,sum(o.order_id)  as total_orders,
sum(case when o.order_status = 'Returned' then 1 else 0 end) as total_returned from orders as o
join order_items as oi on o.order_id = oi.order_id
join customers as c on c.customer_id = o.customer_id
group by 1
)
select cte.*,case when total_returned > 5 then 'Returned' else 'New' end as customer_category from cte


-- 15.Top 5 customers by orders in each state
-- Identify the top 5 customers with the highest number of orders for each state.
-- challenge:include the no of orders and total sales for each customer

select * from(
select c.state,concat(c.first_name,' ',c.last_name) as full_name,
count(o.order_id) as total_orders,sum(total_sale) as total_sale,
dense_rank() over(partition by c.state order by count(o.order_id) desc)  as rank from customers as c 
join orders as o on o.customer_id = c.customer_id
join order_items as oi on o.order_id = oi.order_id
group by 1,2) as t1 where rank < 6



-- 16.Revenue by shipping provider
-- caliculate the total revenue handled by each shipping provider
-- challenge:include the total number of orders handled and the average delivery time for each provider.

select s.shipping_providers,count(o.order_id) as orders_handled,
sum(oi.total_sale) as total_sale ,round(coalesce (avg(s.return_date - s.shipping_date),0),2) as average_days from orders as o
join order_items as oi on o.order_id = oi.order_id
join shippings as s on s.order_id = o.order_id
group by 1


-- 17.Top 10 products with highest decreasing revenue ratio compared to last year and current year
-- challenge:Return product_id,product_name,category_name,2024 revenue and 2025 revenue decrease
-- ratio at the end of result


with last_year as (
select p.product_id,p.product_name,sum(oi.total_sale) as revenue from orders as o
join order_items as oi on o.order_id = oi.order_id
join products as p on p.product_id = oi.product_id
where extract(year from o.order_date) = 2022
group by 1,2),


current_year as (
select p.product_id,p.product_name,sum(oi.total_sale) as revenue from orders as o
join order_items as oi on o.order_id = oi.order_id
join products as p on p.product_id = oi.product_id
where extract(year from o.order_date) = 2023
group by 1,2)


select cs.product_id,ls.revenue as last_year_revenue,
cs.revenue - ls.revenue as revenue_difference,
round((cs.revenue - ls.revenue)::numeric / ls.revenue::numeric * 100,2) as revenue_diff_ratio,
cs.revenue as current_year_revenue from last_year as ls
join current_year as cs on ls.product_id = cs.product_id
where ls.revenue > cs.revenue
order by revenue_diff_ratio desc limit 5


-- Final Task:
-- Stored Procedure
-- create a function as soon as the product is sold the same quantity should reduced from inventory table
-- after adding any sales records it should update the stock in the inventory table based on product
-- and qty purchased



